language: java
sudo: true
jdk:
  - oraclejdk7
  - openjdk7
  
branches:
  only:
    - master
    - Création_de_la_base

before_install:
  - sudo apt-get install librxtx-java
  - cd /usr/lib/jni
  - ls
  - cd /usr/lib/jvm
  - ls
  - cd xGenuini
  - chmod +x gradlew

install:
  - ./gradlew assemble
  - ./gradlew clean compile

notifications:
  email: false
