language: java
sudo: true # faster builds
jdk:
  - oraclejdk7
  - openjdk7
  
branches:
  only:
    - master
    - Création_de_la_base

before_install:
  - cd xGenuini
  - chmod +x gradlew
  
install: true

script:
  - ./gradlew clean compile

notifications:
  email: false
